jobs:
  build:
    docker:
      - image: docker:17.09.0-ce
    steps:
      - run: docker -v
      - run:
        name: "Install docker compose"
        command: sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      - run: docker-compose -v
