version: 2
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: buildpack-deps:jessie
    environment:
       - BASH_ENV: ~/.bashrc
    steps:
      - run: echo "export PATH=/tmp/zomg/:$PATH" > ~/.bashrc

      - run: mkdir zomg
      - run: echo 'echo "Hello, world!"' > zomg/hello
      - run: chmod +x zomg/hello
      - run:
          command: |
            hello

