version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4

    steps:
      - run:
          name: Env
          command: |
            gem env
            bundle env

      - run:
          name: gem install bundler
          command: gem install bundler

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
