version: 2
jobs:
  build:
    working_directory: /opt/project/
    docker:
      - image: docker:stable-git
    branches:
      only:
        - struct
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t org/project:latest .
      - run: docker tag org/project:latest org/project:`git describe`
      - run: docker push org/project:*
