version: 2
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: busybox
    environment:
       - BASH_ENV: ~/.bashrc
    steps:
      - run: echo "export PATH=zomg/:$PATH" > ~/.bashrc

      - run: mkdir zomg
      - run: echo 'echo \"Hello, world!\" > zomg/hello'
      - run: ls -aslh .
      - run: ls -aslh zomg
      - run: "chmod +x zomg/hello"
      - run:
          command: |
            hello

