version: 2
jobs:
  docker:
    - image: circleci/ruby:2.4
  build:
    steps:
      - checkout
      - run:
        name: Create artifact directory
        command: mkdir artifacts
      - run:
        name: Generate some artifact
        command: echo "Hello, world!" > artifact.txt
      - store_artifacts:
        path: artifacts/

workflows:
  version: 2

  btd:
    jobs:
      - build
