version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - run: |
          curl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh \
            --fail --show-error | sudo bash
      - run: which circleci
      - run: circleci version
      - run: circleci-agent version
      - run: circleci tests glob ".circleci/*" circleci tests split
      - run: |
          echo $(circleci tests glob ".circleci/**/*")
          circleci tests glob ".circleci/**/*" | xargs -n 1 echo
      - run: |
          echo $(circleci-agent tests glob ".circleci/**/*")
          circleci-agent tests glob ".circleci/**/*" | xargs -n 1 echo
      - run: circleci step halt
  use-machine:
    machine: true
    steps:
      - checkout
      - run: |
          curl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh \
            --fail --show-error | sudo bash
      - run: which circleci
      - run: circleci version
      - run: circleci-agent version
      - run: |
          echo $(circleci tests glob ".circleci/**/*")
          circleci tests glob ".circleci/**/*" | xargs -n 1 echo
      - run: circleci step halt
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - use-machine
