version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.1.0"

    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Output installed rubies
          command: chruby

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
