version: 2
jobs:
  flow:
    working_directory: /tmp
    docker:
      - image: buildpack-deps:jessie
    steps:
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output

      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output

  downstream:
    working_directory: /tmp
    docker:
      - image: buildpack-deps:jessie
    steps:
      - run: mkdir -p /tmp/workspace
      - attach_workspace:
          at: /tmp/workspace

      - run: |
          if [ cat workspace/echo-output == "Hello, world!" ]
            echo "It worked!"
          fi

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
