version: 2.0
orbs:
  cli: circleci/circleci-cli@dev:volatile

jobs:
  build:
    docker:
      - image: circleci/golang:latest
    environment:
      - USER: circleci
      - TRAVIS: circleci
    steps:
      - run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      - run: |
          $HOME/.linuxbrew/bin/brew bump-formula-pr --dry-run \
            --url=https://github.com/CircleCI-Public/circleci-cli.git \
            --tag=v1.0.0 \
            --revision=$CIRCLE_SHA \
            circleci

workflows:
  version: 2
  workflow:
    jobs:
      - build
