version: 2
jobs:
  build:
    macos:
      xcode: "9.1.0"

    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Output installed rubies
          command: chruby

      - run:
          name: Filename limit prodding
          command: |
            ruby -e'f="";100.times{|i|f<<"#{i}"};system("touch #{f}")'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
