version: 2.1
orbs:
  cli: circleci/circleci-cli@dev:volatile

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - cli/install
      - run: which circleci
      - run: circleci version
      - run: circleci-agent version
      - run: circleci tests glob ".circleci/*" circleci tests split
      - run: |
          echo $(circleci tests glob ".circleci/**/*")
          circleci tests glob ".circleci/**/*" | xargs -n 1 echo
      - run: |
          echo $(circleci-agent tests glob ".circleci/**/*")
          circleci-agent tests glob ".circleci/**/*" | xargs -n 1 echo
      - run: circleci step halt
  use-image:
    executor:
      name: cli/default
      tag: 0.1.1640
    steps:
      - checkout
      - run: which circleci
      - run: circleci version
      - run: circleci-agent version
      - run: |
          echo $(circleci tests glob ".circleci/**/*")
          circleci tests glob ".circleci/**/*" | xargs -n 1 echo
      - run: circleci step halt
  use-machine:
    machine: true
    steps:
      - checkout
      - cli/install
      - run: which circleci
      - run: circleci version
      - run: circleci-agent version
      - run: |
          echo $(circleci tests glob ".circleci/**/*")
          circleci tests glob ".circleci/**/*" | xargs -n 1 echo
      - run: circleci step halt
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - use-image
      - use-machine
